import type { Metadata } from "next";
import { Inter, Poppins, Geist } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";
import { cn } from "@/lib/utils";
import Footer from "@/components/shared/footer";
import Container from "@/components/layout/container";
import { ReactNode } from "react";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("dark", "font-sans", geist.variable)}>
      <body
        className={`${inter.variable} ${poppins.variable} antialiased h-screen  overflow-hidden`}
      >
        <Main>{children}</Main>
        {/* Radials */}
        <div className="rectangle top-80 lg:top-140 -left-18 hidden lg:block"></div>
        <div className="rectangle  -top-10  lg:-top-40 -right-96 hidden lg:block"></div>
      </body>
    </html>
  );
}

export function Main({ children }: { children: ReactNode }) {
  return (
    <div className="h-full overflow-y-auto">
      <Header />

      <Container>{children}</Container>
    </div>
  );
}
