import type { Metadata } from "next";
import {  Inter, Poppins, Geist } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins(
 {
  variable:"--font-poppins",
  weight:["400","500","600","700","800","900"],
 }  
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("dark", "font-sans", geist.variable)}>
      <body
        className={`${inter.variable} ${poppins.variable} antialiased h-screen overflow-hidden `}
      >
        <Header/>

        {children}
        <div className="rectangle absolute top-140 -left-18"></div>
          <div className="rectangle absolute -top-28 -right-20"></div>
      </body>
    </html>
  );
}